/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fi.ston.models

import fi.ston.models.AssetInfoSchema
import fi.ston.models.OperationStat

import com.squareup.moshi.Json
import com.squareup.moshi.JsonClass

/**
 * 
 *
 * @param asset0Info 
 * @param asset1Info 
 * @param operation 
 */


data class OperationsInfo (

    @Json(name = "asset0_info")
    val asset0Info: AssetInfoSchema,

    @Json(name = "asset1_info")
    val asset1Info: AssetInfoSchema,

    @Json(name = "operation")
    val operation: OperationStat

)

