/**
 *
 * Please note:
 * This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * Do not edit this file manually.
 *
 */

@file:Suppress(
    "ArrayInDataClass",
    "EnumEntryName",
    "RemoveRedundantQualifierName",
    "UnusedImport"
)

package fi.ston.apis

import java.io.IOException
import okhttp3.OkHttpClient
import okhttp3.HttpUrl

import fi.ston.models.GetWalletAddress200Response

import com.squareup.moshi.Json

import fi.ston.infrastructure.ApiClient
import fi.ston.infrastructure.ApiResponse
import fi.ston.infrastructure.ClientException
import fi.ston.infrastructure.ClientError
import fi.ston.infrastructure.ServerException
import fi.ston.infrastructure.ServerError
import fi.ston.infrastructure.MultiValueMap
import fi.ston.infrastructure.PartConfig
import fi.ston.infrastructure.RequestConfig
import fi.ston.infrastructure.RequestMethod
import fi.ston.infrastructure.ResponseType
import fi.ston.infrastructure.Success
import fi.ston.infrastructure.toMultiValue

class JettonApi(basePath: kotlin.String = defaultBasePath, client: OkHttpClient = ApiClient.defaultClient) : ApiClient(basePath, client) {
    companion object {
        @JvmStatic
        val defaultBasePath: String by lazy {
            System.getProperties().getProperty(ApiClient.baseUrlKey, "http://localhost")
        }
    }

    /**
     * 
     * 
     * @param addrStr 
     * @param ownerAddress Address of the owner
     * @return GetWalletAddress200Response
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     * @throws UnsupportedOperationException If the API returns an informational or redirection response
     * @throws ClientException If the API returns a client error response
     * @throws ServerException If the API returns a server error response
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class, UnsupportedOperationException::class, ClientException::class, ServerException::class)
    fun getWalletAddress(addrStr: kotlin.String, ownerAddress: kotlin.String) : GetWalletAddress200Response {
        val localVarResponse = getWalletAddressWithHttpInfo(addrStr = addrStr, ownerAddress = ownerAddress)

        return when (localVarResponse.responseType) {
            ResponseType.Success -> (localVarResponse as Success<*>).data as GetWalletAddress200Response
            ResponseType.Informational -> throw UnsupportedOperationException("Client does not support Informational responses.")
            ResponseType.Redirection -> throw UnsupportedOperationException("Client does not support Redirection responses.")
            ResponseType.ClientError -> {
                val localVarError = localVarResponse as ClientError<*>
                throw ClientException("Client error : ${localVarError.statusCode} ${localVarError.message.orEmpty()}", localVarError.statusCode, localVarResponse)
            }
            ResponseType.ServerError -> {
                val localVarError = localVarResponse as ServerError<*>
                throw ServerException("Server error : ${localVarError.statusCode} ${localVarError.message.orEmpty()} ${localVarError.body}", localVarError.statusCode, localVarResponse)
            }
        }
    }

    /**
     * 
     * 
     * @param addrStr 
     * @param ownerAddress Address of the owner
     * @return ApiResponse<GetWalletAddress200Response?>
     * @throws IllegalStateException If the request is not correctly configured
     * @throws IOException Rethrows the OkHttp execute method exception
     */
    @Suppress("UNCHECKED_CAST")
    @Throws(IllegalStateException::class, IOException::class)
    fun getWalletAddressWithHttpInfo(addrStr: kotlin.String, ownerAddress: kotlin.String) : ApiResponse<GetWalletAddress200Response?> {
        val localVariableConfig = getWalletAddressRequestConfig(addrStr = addrStr, ownerAddress = ownerAddress)

        return request<Unit, GetWalletAddress200Response>(
            localVariableConfig
        )
    }

    /**
     * To obtain the request config of the operation getWalletAddress
     *
     * @param addrStr 
     * @param ownerAddress Address of the owner
     * @return RequestConfig
     */
    fun getWalletAddressRequestConfig(addrStr: kotlin.String, ownerAddress: kotlin.String) : RequestConfig<Unit> {
        val localVariableBody = null
        val localVariableQuery: MultiValueMap = mutableMapOf<kotlin.String, kotlin.collections.List<kotlin.String>>()
            .apply {
                put("owner_address", listOf(ownerAddress.toString()))
            }
        val localVariableHeaders: MutableMap<String, String> = mutableMapOf()
        localVariableHeaders["Accept"] = "application/json"

        return RequestConfig(
            method = RequestMethod.GET,
            path = "/v1/jetton/{addr_str}/address".replace("{"+"addr_str"+"}", encodeURIComponent(addrStr.toString())),
            query = localVariableQuery,
            headers = localVariableHeaders,
            requiresAuthentication = false,
            body = localVariableBody
        )
    }


    private fun encodeURIComponent(uriComponent: kotlin.String): kotlin.String =
        HttpUrl.Builder().scheme("http").host("localhost").addPathSegment(uriComponent).build().encodedPathSegments[0]
}
